default_platform(:ios)

platform :ios do
  desc "Export ipa"
  lane :export_ipa do
    keychain_password = SecureRandom.uuid
    create_keychain(
      name: "ios-build.keychain",
      password: keychain_password,
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )
    if ENV["CERTIFICATE_SPLIT"] == '1'
      import_certificate(
        certificate_path: "ios-build-key.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "ios-build.keychain",
        keychain_password: keychain_password,
        log_output: true
      )
      import_certificate(
        certificate_path: "ios-build-key.cer",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "ios-build.keychain",
        keychain_password: keychain_password,
        log_output: true
      )
    else
      import_certificate(
        certificate_path: "ios-build.p12",
        certificate_password: ENV["CERTIFICATE_PASSWORD"],
        keychain_name: "ios-build.keychain",
        keychain_password: keychain_password,
        log_output: true
      )
    end
    install_provisioning_profile(
      path: "ios-build.mobileprovision"
    )
    disable_targets = ENV["DISABLE_TARGETS"]&.split(/,/)
    update_code_signing_settings(
      use_automatic_signing: false,
      path: ENV["PROJECT_PATH"],
      targets: disable_targets
    )
    update_project_provisioning(
      xcodeproj: ENV["PROJECT_PATH"],
      profile: "ios-build.mobileprovision",
      code_signing_identity: ENV["CODE_SIGNING_IDENTITY"],
      target_filter: disable_targets&.map{|target| "^#{Regexp.escape(target)}$" }.join("|")
    )
    update_project_team(
      path: ENV["PROJECT_PATH"],
      teamid: ENV["TEAM_ID"],
      targets: disable_targets
    )
    if ENV["WORKSPACE_PATH"] != ""
      build_app(
        workspace: ENV["WORKSPACE_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_directory: File.dirname(ENV["OUTPUT_PATH"]),
        output_name: File.basename(ENV["OUTPUT_PATH"]),
        clean: true,
        export_method: ENV["EXPORT_METHOD"]
      )
    else
      build_app(
        project: ENV["PROJECT_PATH"],
        configuration: ENV["CONFIGURATION"],
        scheme: ENV["SCHEME"],
        output_directory: File.dirname(ENV["OUTPUT_PATH"]),
        output_name: File.basename(ENV["OUTPUT_PATH"]),
        clean: true,
        export_method: ENV["EXPORT_METHOD"]
      )
    end
    delete_keychain(
      name: "ios-build.keychain"
    )
  end
end
